apiVersion: v1
kind: Service
metadata:
  name: cloud-gitops-node-service
spec:
  selector:
    app: cloud-gitops-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
